### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by noracami** [side-project-at-SPT/split-front#10]
https://github.com/side-project-at-SPT/split-front/blob/b02e0fb6ee89a924273093b8bae1082cfa6eaecd/src/views/RoomView.vue#L288

```
error: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1

1.991     at async PluginDriver.hookFirstAndGetPlugin (file:///src/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)

1.991     at async file:///src/node_modules/rollup/dist/es/shared/node-entry.js:24611:75

1.991     at async Queue.work (file:///src/node_modules/rollup/dist/es/shared/node-entry.js:25654:32)

------

#13 1.984 [vite:asset] Could not load /src/src/assets/roomPLayers/ready.svg (imported by src/views/RoomView.vue): ENOENT: no such file or directory, open '/src/src/assets/roomPLayers/ready.svg'

#13 1.991 error during build:

#13 1.991 Error: Could not load /src/src/assets/roomPLayers/ready.svg (imported by src/views/RoomView.vue): ENOENT: no such file or directory, open '/src/src/assets/roomPLayers/ready.svg'

#13 1.991     at async open (node:internal/fs/promises:639:25)

#13 1.991     at async Object.readFile (node:internal/fs/promises:1242:14)

#13 1.991     at async fileToBuiltUrl (file:///src/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:16283:21)

#13 1.991     at async Object.load (file:///src/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:16164:25)

#13 1.991     at async PluginDriver.hookFirstAndGetPlugin (file:///src/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)

#13 1.991     at async file:///src/node_modules/rollup/dist/es/shared/node-entry.js:24611:75

#13 1.991     at async Queue.work (file:///src/node_modules/rollup/dist/es/shared/node-entry.js:25654:32)

Failed to build with zeaburpack: run buildctl build: exit status 1
```

**Comment by noracami** [comment]
fixed via 2a3747d8e32054b244fff82a54911f3f95f3d256 .
